-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 19:10:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lista_Amici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lista_Amici` (
  `idLista_Amici` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Lista_Utenti` INT NOT NULL,
  PRIMARY KEY (`idLista_Amici`),
  INDEX `Lista_Utenti_idx` (`Lista_Utenti` ASC),
  CONSTRAINT `Lista_Utenti`
    FOREIGN KEY (`Lista_Utenti`)
    REFERENCES `mydb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Luogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Luogo` (
  `idLuogo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Città` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLuogo`),
  UNIQUE INDEX `idLuogo_UNIQUE` (`idLuogo` ASC),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lista_Luoghi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lista_Luoghi` (
  `idLista_Luoghi` INT UNSIGNED NOT NULL,
  `Luoghi` VARCHAR(45) NOT NULL,
  `Lista_Luoghi` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLista_Luoghi`),
  CONSTRAINT `Lista_Luoghi`
    FOREIGN KEY (`idLista_Luoghi`)
    REFERENCES `mydb`.`Luogo` (`idLuogo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utente` (
  `idUtente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Sesso` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Data` DATE NULL,
  `Lista_Amici` INT UNSIGNED NULL,
  `Lista_Luoghi` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUtente`),
  UNIQUE INDEX `idUtente_UNIQUE` (`idUtente` ASC),
  UNIQUE INDEX `Lista_Amici_UNIQUE` (`Lista_Amici` ASC),
  INDEX `Lista_Luoghi_idx` (`Lista_Luoghi` ASC),
  CONSTRAINT `Lista_Amici`
    FOREIGN KEY (`Lista_Amici`)
    REFERENCES `mydb`.`Lista_Amici` (`idLista_Amici`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Lista_Luoghi`
    FOREIGN KEY (`Lista_Luoghi`)
    REFERENCES `mydb`.`Lista_Luoghi` (`idLista_Luoghi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
